### ISSUE TITLE
Comments on draft notebooks

### ISSUE THREAD

**Issue by mdpiper** [CodeToCommunicate/CoCoTerm1#1]
Hi @isamarcortes! These are some comments on the draft notebooks that you've prepared. Please let me know what you think. I'm happy to help work on any of these notebooks, just let me know.

1. Maybe use a different library than `numpy` to introduce the concept of libraries in the Session 2 notebook, just because it'll be covered in more detail in Session 4. Possibly `os`?
2. Session 2 needs a section about containers, like lists and dictionaries.
3. I'd recommend the Session 2 notebook have the level 1 title Python Elements, then level 2 headings LIbraries, Data Types, Containers, Loops, Conditionals, Homework.
3. I'm nervous about the second practice example in the Session 3 notebook. It sideways introduces the concept of a module, so it strays from the topic of functions. Also, how does it work?
4. It feels like the first part of the Session 4 notebook could go in Session 2 for the discussion of libraries, which will help keep the focus of the session on using `numpy` and `pandas`.
6. The Session 5 notebook could use a sentence or two explaining why we're looking at two plotting libraries, `matplotlib` and `seaborn`.

**Comment by santisoler** [comment]
@aguspesce I would recommend using ReviewNB: https://www.reviewnb.com/

You would need to configure it for this repo, so we can leave comments to notebooks through their UI.

**Comment by mdpiper** [comment]
All of the concerns I raised above have been addressed, so I'm closing this issue.
